# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# SM_RUN_RESULT
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set SM_RUN_RESULT to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# SM_RUN_RESULT__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set SM_RUN_RESULT__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The SM_COMPILE_RESULT variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/salldritt/workspace/ros2/ros2_humble_android_ws/src/eProsima/Fast-DDS/cmake/modules/check_shared_mutex_priority.cpp
# Executable    : /home/salldritt/workspace/ros2/ros2_humble_android_ws/build/fastrtps/CMakeFiles/cmTC_2a3fd-SM_RUN_RESULT
# Run arguments : 
#    Called from: [1]	/home/salldritt/workspace/ros2/ros2_humble_android_ws/src/eProsima/Fast-DDS/src/cpp/CMakeLists.txt

set( SM_RUN_RESULT 
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( SM_RUN_RESULT__TRYRUN_OUTPUT 
     "PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP"
     CACHE STRING "Output from TRY_RUN" FORCE)

